/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lp.paintbrush.tela;

import java.awt.event.MouseEvent;
import lp.paintbrush.classes.Cilindro;
import lp.paintbrush.classes.Circulo;
import lp.paintbrush.classes.Piramide;
import lp.paintbrush.classes.Poligono;
import lp.paintbrush.classes.Ponto;
import lp.paintbrush.classes.Retangulo;
import lp.paintbrush.classes.Spray;

public class FrPaint extends javax.swing.JFrame {

    enum TipoFigura {
        tpPonto, tpRetangulo, tpCirculo, tpCilindro, tpPiramide, tpSpray, tpPoligono
    };

    Ponto p = new Ponto();
    Retangulo r = new Retangulo();
    Circulo c = new Circulo();
    Cilindro cl = new Cilindro();
    Piramide pr = new Piramide();
    Poligono po = new Poligono();
    Spray sp = new Spray();

    private TipoFigura tipoFigura = TipoFigura.tpPonto;

    /**
     * Creates new form FrPaint
     */
    public FrPaint() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTela = new javax.swing.JPanel();
        btnPonto = new javax.swing.JButton();
        jColorChooser = new javax.swing.JColorChooser();
        jpCor = new javax.swing.JPanel();
        jpCorInterna = new javax.swing.JPanel();
        cbArea = new java.awt.Checkbox();
        btnRetangulo = new javax.swing.JButton();
        btnCirculo = new javax.swing.JButton();
        btnCilindro = new javax.swing.JButton();
        btnPiramide = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSpray = new javax.swing.JButton();
        btnPoligono = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpTela.setBackground(new java.awt.Color(204, 255, 255));
        jpTela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpTelaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jpTelaMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jpTelaLayout = new javax.swing.GroupLayout(jpTela);
        jpTela.setLayout(jpTelaLayout);
        jpTelaLayout.setHorizontalGroup(
            jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpTelaLayout.setVerticalGroup(
            jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnPonto.setText("Ponto");
        btnPonto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPonto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPontoMouseClicked(evt);
            }
        });

        jColorChooser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jpCor.setBackground(new java.awt.Color(0, 0, 0));
        jpCor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpCor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpCorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpCorLayout = new javax.swing.GroupLayout(jpCor);
        jpCor.setLayout(jpCorLayout);
        jpCorLayout.setHorizontalGroup(
            jpCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jpCorLayout.setVerticalGroup(
            jpCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jpCorInterna.setBackground(new java.awt.Color(51, 51, 255));
        jpCorInterna.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpCorInterna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpCorInternaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpCorInternaLayout = new javax.swing.GroupLayout(jpCorInterna);
        jpCorInterna.setLayout(jpCorInternaLayout);
        jpCorInternaLayout.setHorizontalGroup(
            jpCorInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jpCorInternaLayout.setVerticalGroup(
            jpCorInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        cbArea.setLabel("Area");

        btnRetangulo.setText("Retangulo");
        btnRetangulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRetangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetanguloActionPerformed(evt);
            }
        });

        btnCirculo.setText("Circulo");
        btnCirculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCirculoActionPerformed(evt);
            }
        });

        btnCilindro.setText("Cilindro");
        btnCilindro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCilindro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCilindroActionPerformed(evt);
            }
        });

        btnPiramide.setText("Piramide");
        btnPiramide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPiramide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiramideActionPerformed(evt);
            }
        });

        jLabel1.setText("Cor do contorno");

        jLabel2.setText("Cor interna");

        btnSpray.setText("Spray");
        btnSpray.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSpray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSprayActionPerformed(evt);
            }
        });

        btnPoligono.setText("Poligono");
        btnPoligono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPoligono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoligonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jColorChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnSpray, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRetangulo, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                .addComponent(btnCirculo, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                .addComponent(btnCilindro, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                .addComponent(btnPonto, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                .addComponent(btnPiramide, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                .addComponent(cbArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPoligono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jpCorInterna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jpCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbArea, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addGap(3, 3, 3)
                        .addComponent(btnPonto, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRetangulo, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCirculo, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCilindro, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPiramide, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSpray, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPoligono, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpCorInterna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jColorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPontoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPontoMouseClicked
        // TODO add your handling code here:
        tipoFigura = TipoFigura.tpPonto;
    }//GEN-LAST:event_btnPontoMouseClicked

    private void jpTelaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpTelaMousePressed
        if (null != tipoFigura)
            switch (tipoFigura) {
                case tpPonto:
                    p.setX(evt.getX());
                    p.setY(evt.getY());
                    p.setCor(jpCor.getBackground());
                    p.desenha(jpTela.getGraphics());
                    break;
                case tpRetangulo:
                    r.setX(evt.getX());
                    r.setY(evt.getY());
                    break;
                case tpCirculo:
                    c.setX(evt.getX());
                    c.setY(evt.getY());
                    break;
                case tpCilindro:
                    cl.setX(evt.getX());
                    cl.setY(evt.getY());
                    break;
                case tpPiramide:
                    pr.setX(evt.getX());
                    pr.setY(evt.getY());
                    break;
                case tpSpray:
                    sp.setCor(jpCor.getBackground());
                    sp.setX(evt.getX());
                    sp.setY(evt.getY());
                    sp.desenha(jpTela.getGraphics());
                    break;
                case tpPoligono:
                    po.setX(evt.getX());
                    po.setY(evt.getY());
                    po.setCor(jpCor.getBackground());
                    po.desenha(jpTela.getGraphics());
                    if (evt.getButton() == MouseEvent.BUTTON3) {
                        po.pegarPontos(jpTela.getGraphics());
                        po.limparPontos();
                    }
                    break;
                default:
                    break;
            }
    }//GEN-LAST:event_jpTelaMousePressed

    private void jpTelaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpTelaMouseReleased
        if (null != tipoFigura)
            switch (tipoFigura) {
                case tpRetangulo:
                    r.setBase(evt.getX() - r.getX());
                    r.setLargura(evt.getY() - r.getY());
                    r.setCor(jpCor.getBackground());
                    r.setCorInterna(jpCorInterna.getBackground());
                    r.setShowArea(cbArea.getState());
                    r.desenha(jpTela.getGraphics());
                    break;
                case tpCirculo:
                    c.setRaio((evt.getX() - c.getX()) / 2);
                    c.setCor(jpCor.getBackground());
                    c.setCorInterna(jpCorInterna.getBackground());
                    c.setShowArea(cbArea.getState());
                    c.desenha(jpTela.getGraphics());
                    break;
                case tpCilindro:
                    cl.setRaio((evt.getX() - cl.getX()) / 2);
                    cl.setAltura(evt.getX() - cl.getX());
                    cl.setCor(jpCor.getBackground());
                    cl.setCorInterna(jpCorInterna.getBackground());
                    cl.setShowArea(cbArea.getState());
                    cl.desenha(jpTela.getGraphics());
                    break;
                case tpPiramide:
                    pr.setBase(evt.getX() - pr.getX());
                    pr.setLargura(evt.getY() - pr.getY());
                    pr.setAltura(2 * pr.getLargura());
                    pr.setCor(jpCor.getBackground());
                    pr.setCorInterna(jpCorInterna.getBackground());
                    pr.setShowArea(cbArea.getState());
                    pr.desenha(jpTela.getGraphics());
                    break;
                default:
                    break;
            }
    }//GEN-LAST:event_jpTelaMouseReleased

    private void btnRetanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetanguloActionPerformed
        // TODO add your handling code here:
        tipoFigura = TipoFigura.tpRetangulo;
    }//GEN-LAST:event_btnRetanguloActionPerformed

    private void btnCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCirculoActionPerformed
        // TODO add your handling code here:
        tipoFigura = TipoFigura.tpCirculo;
    }//GEN-LAST:event_btnCirculoActionPerformed

    private void btnCilindroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCilindroActionPerformed
        // TODO add your handling code here:
        tipoFigura = TipoFigura.tpCilindro;
    }//GEN-LAST:event_btnCilindroActionPerformed

    private void btnPiramideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiramideActionPerformed
        // TODO add your handling code here:
        tipoFigura = TipoFigura.tpPiramide;
    }//GEN-LAST:event_btnPiramideActionPerformed

    private void jpCorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCorMouseClicked
        // TODO add your handling code here:
        jpCor.setBackground(jColorChooser.getColor());
    }//GEN-LAST:event_jpCorMouseClicked

    private void jpCorInternaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCorInternaMouseClicked
        // TODO add your handling code here:
        jpCorInterna.setBackground(jColorChooser.getColor());
    }//GEN-LAST:event_jpCorInternaMouseClicked

    private void btnSprayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSprayActionPerformed
        // TODO add your handling code here:
        tipoFigura = TipoFigura.tpSpray;
    }//GEN-LAST:event_btnSprayActionPerformed

    private void btnPoligonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoligonoActionPerformed
        // TODO add your handling code here:
        tipoFigura = TipoFigura.tpPoligono;
    }//GEN-LAST:event_btnPoligonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrPaint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCilindro;
    private javax.swing.JButton btnCirculo;
    private javax.swing.JButton btnPiramide;
    private javax.swing.JButton btnPoligono;
    private javax.swing.JButton btnPonto;
    private javax.swing.JButton btnRetangulo;
    private javax.swing.JButton btnSpray;
    private java.awt.Checkbox cbArea;
    private javax.swing.JColorChooser jColorChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jpCor;
    private javax.swing.JPanel jpCorInterna;
    private javax.swing.JPanel jpTela;
    // End of variables declaration//GEN-END:variables
}
